<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="<?php echo BASE_URL . '/css/app.css'?>">
    <script src="<?php echo BASE_URL . '/js/app.js'?>"></script>
    <title>Dendroid Skeleton Application</title>
</head>
<body>

<div class="container mt-4">
    <div spf="flash-messenger"></div>
    <div spf="main-content">Main Content</div>
</div>

</body>
</html>