
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete confirmation</h5>
            </div>
            <div class="modal-body">
                <p>Please confirm that you want to delete this item?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button id="delete-confirm-button" type="button" class="btn btn-primary">Confirm</button>
            </div>
        </div>
    </div>
</div>

<form spf="delete-confirmation-form">
    <input spf="form-id"/>
</form>

<script>
    $( document ).ready(function () {
        const form = $('#delete-confirmation-form');

        $('.card-link.delete').click(function () {
            const id = this.getAttribute('data-id');
            const input = form.find('input[name=id]');
            input.val(id);
        });

        $('#delete-confirm-button').click(function() {
            form.submit();
        });
    });
</script>