<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="<?php echo BASE_URL . '/css/app.css'?>">
    <script src="<?php echo BASE_URL . '/js/app.js'?>"></script>
    <title>Dendroid Skeleton Application</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Dendroid Skeleton Application</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="<?php echo $this->routing->createUrl('\App\Component\Note\Index');?>">Notes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<?php echo $this->routing->createUrl('\App\Component\Note\Create');?>">Create New</a>
            </li>
        </ul>
    </div>
</nav>

<div class="container mt-4">
    <div spf="flash-messenger"></div>
    <div spf="main-content">Main Content</div>
</div>

</body>
</html>